// LOCALHOST 
### Get all employees
 
GET http://localhost:3001/employees

### Get contact by id 
GET http://localhost:3001/employees/67945cad4e39ba0930a6158e

### CREATE contact 
POST http://localhost:3001/employees HTTP/1.1 
content-type: application/json

{
    "firstname": "Hannah",
    "lastname": "White",
    "badgenumber": "33445",
    "department": "Admin",
    "shift": "Morning"
}

### PUT/UPDATE contact 
PUT http://localhost:3001/employees/6795603fe1aa7ce9574d2b2c HTTP/1.1 
content-type: application/json

{
    "firstname": "Isaac",
    "lastname": "Davis",
    "badgenumber": "66778",
    "department": "Procurement",
    "shift": "Afternoon"
} 

### DELETE contact 
DELETE http://localhost:3001/employees/67955e6dcf5e13b32d4080c0 HTTP/1.1

