// LOCALHOST 
### Get all employees
 
GET http://localhost:3001/employees

### Get contact by id 
GET http://localhost:3001/employees/67945cad4e39ba0930a6158e

### CREATE contact 
POST http://localhost:3001/employees HTTP/1.1 
content-type: application/json

{
    "firstname": "Liam",
    "lastname": "Garcia",
    "badgenumber": "44321",
    "department": "IT",
    "shift": "Afternoon",
    "location": "Unknown",
    "status": "Active"
}

### PUT/UPDATE contact 
PUT http://localhost:3001/employees/67956f44671b463256fce1b7 HTTP/1.1 
content-type: application/json

{
    "firstname": "Katherine",
    "lastname": "Harris",
    "badgenumber": "11234",
    "department": "Finance",
    "shift": "Morning",
    "location": "Unknown",
    "status": "Active"
} 

### DELETE contact 
DELETE http://localhost:3001/employees/67945cad4e39ba0930a61590 HTTP/1.1

